- name: 'dependencies'
  color: 'F2F2F2'
  description: '[Build Update] Pull requests that update a dependency file.'
- name: 'deployment'
  color: 'F2F2F2'
  description: '[Build Update] Pull requests that create a deployment.'
- name: 'bug'
  color: '00DBAB'
  description: "[Problem] Something isn't working or looking right."
- name: 'question'
  color: '00DBAB'
  description: '[Problem] Further help and/or information is required.'
- name: 'feature'
  color: '009EDB'
  description: '[Improvement] New or enhanced feature.'
- name: 'data'
  color: '009EDB'
  description: '[Improvement] Request for data, analysis or reports.'
- name: 'test'
  color: '009EDB'
  description: '[Improvement] Anything related to testing or tests.'
- name: 'documentation'
  color: '009EDB'
  description: '[Improvement] Anything relating to documentation.'
- name: 'wont-fix'
  color: '4D4D4D'
  description: '[Inactive] This will not be worked on.'
- name: 'duplicate'
  color: '4D4D4D'
  description: '[Inactive] This issue or pull request already exists.'
- name: 'HIGH PRIORITY'
  color: 'DB3E00'
  description: '[PRIORITY] This issue is a high priority.'
