- name: 'dependencies'
  color: 'E6E6E6'
  description: '[Build Update] Pull requests that update a dependency file.'
- name: 'deployment'
  color: 'E6E6E6'
  description: '[Build Update] Pull requests that create a deployment.'
- name: 'bug'
  color: 'FB3640'
  description: "[Problem] Something isn't working or looking right."
- name: 'question'
  color: 'FB3640'
  description: '[Problem] Further help and/or information is required.'
- name: 'feature'
  color: '5B92E5'
  description: '[Improvement] New or enhanced feature.'
- name: 'test'
  color: '5B92E5'
  description: '[Improvement] Anything related to testing or tests.'
- name: 'documentation'
  color: '5B92E5'
  description: '[Improvement] Anything relating to documentation.'
- name: 'wont-fix'
  color: '1C1C1C'
  description: '[Inactive] This will not be worked on.'
- name: 'duplicate'
  color: '1C1C1C'
  description: '[Inactive] This issue or pull request already exists.'
- name: 'HIGH PRIORITY'
  color: 'AA0000'
  description: '[PRIORITY] This issue is a high priority.'
