version: v1

labels:
    - label: 'feature'
      sync: true
      matcher:
          title: '^feat: .*'

    - label: 'bug'
      sync: true
      matcher:
          title: '^fix: .*'

    - label: 'dependencies'
      sync: true
      matcher:
          title: '^build(dependencies): .*'

    - label: 'test'
      sync: true
      matcher:
          title: '^test: .*'

    - label: 'documentatiokn'
      sync: true
      matcher:
          title: '^docs: .*'
