name: automatically add to project board
on:
    workflow_call:
        secrets:
            TOKEN:
                required: true

env:
    project: https://github.com/orgs/road86/projects/3
    todo: Todo
    done: Done
    in_progress: In Progress
    for_review: For Review

jobs:
    issue_opened:
        name: add newly opened Issue to project as Todo
        runs-on: ubuntu-latest
        if: github.event_name == 'issues' && github.event.action == 'opened'
        steps:
            - name: mark issue as ${{ env.todo }}
              uses: actions/add-to-project@main
              with:
                  project-url: ${{ env.project }}
                  github-token: ${{ secrets.TOKEN }}
                  labeled: env.todo
                  id: add-project
            - name: mark PR as ${{ env.for_review }}
              uses: titoportas/update-project-fields@v0.1.0
              with:
                project-url: ${{ env.project }}
                github-token: ${{ secrets.TOKEN }}
                item-id: ${{ steps.add-project.outputs.itemId }}
                field-keys: Status
                field-values: ${{ env.todo }}
    pr_opened:
        name: add opened or reopened PR to project as For Review
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        steps:
            - name: add PR to project board
              uses: actions/add-to-project@main
              with:
                  project-url: ${{ env.project }}
                  github-token: ${{ secrets.TOKEN }}
                  labeled: env.for_review
                  id: add-project
            - name: mark PR as ${{ env.for_review }}
              uses: titoportas/update-project-fields@v0.1.0
              with:
                project-url: ${{ env.project }}
                github-token: ${{ secrets.TOKEN }}
                item-id: ${{ steps.add-project.outputs.itemId }}
                field-keys: Status
                field-values: ${{ env.for_review }}
