name: Set Repo Label List

on:
    workflow_call:
        secrets:
            TOKEN:
                required: true

jobs:
    synchronise_labels:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: synchronize labels
              uses: julbme/gh-action-manage-label@v1
              with:
                  from: https://raw.githubusercontent.com/road86/.github/main/.github/labels.yml
                  skip_delete: true
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN  }}
